<?php

/**
 * @author Richard Weinhold
 */

declare(strict_types=1);

namespace ricwein\FileSystem;

use ricwein\FileSystem\Enum\Hash;
use ricwein\FileSystem\Exceptions\FileNotFoundException;
use ricwein\FileSystem\Exceptions\UnsupportedException;
use ricwein\FileSystem\Helper\Constraint;
use ricwein\FileSystem\Helper\DirectoryIterator;
use ricwein\FileSystem\Exceptions\AccessDeniedException;
use ricwein\FileSystem\Exceptions\UnexpectedValueException;

/**
 * represents a selected directory
 */
class Directory extends FileSystem
{
    /**
     * @noinspection PhpDocFieldTypeMismatchInspection
     * @var Storage\Disk
     */
    protected Storage $storage;

    /**
     * @inheritDoc
     * @param Storage $storage
     * @param int $constraints
     * @throws AccessDeniedException
     * @throws Exceptions\RuntimeException
     * @throws UnexpectedValueException
     * @throws UnsupportedException
     */
    public function __construct(Storage $storage, int $constraints = Constraint::STRICT)
    {
        if ($storage instanceof Storage\Memory) {
            throw new UnsupportedException('In-memory directories are not supported.', 500);
        }

        if ($storage instanceof Storage\Stream) {
            throw new UnsupportedException('Stream directories are not supported.', 500);
        }

        if ($storage instanceof Storage\Disk\Temp && !$storage->isDir() && !$storage->mkdir()) {
            throw new AccessDeniedException('Unable to create temp directory.', 500);
        }

        parent::__construct($storage, $constraints);
    }

    /**
     * @throws Exceptions\ConstraintsException
     * @throws Exceptions\RuntimeException
     * @throws FileNotFoundException
     * @throws UnexpectedValueException
     */
    protected function checkFileReadPermissions(): void
    {
        if (!$this->isDir() || !$this->isReadable()) {
            throw new FileNotFoundException(sprintf('Unable to open directory: "%s".', $this->storage instanceof Storage\Disk ? $this->storage->path()->raw : get_class($this->storage)), 404);
        }

        parent::checkFileReadPermissions(); // TODO: Change the autogenerated stub
    }

    /**
     * create new dir if not exists
     * @return self
     * @throws AccessDeniedException
     * @throws Exceptions\ConstraintsException
     * @throws Exceptions\RuntimeException
     * @throws UnexpectedValueException
     */
    public function mkdir(): self
    {
        if (!$this->storage->doesSatisfyConstraints()) {
            throw $this->storage->getConstraintViolations();
        }

        if (!$this->storage->isDir() && !$this->storage->mkdir()) {
            throw new AccessDeniedException(sprintf('unable to create directory at: "%s"', $this->storage->path()->raw), 500);
        }

        return $this;
    }

    /**
     * @inheritDoc
     * @return FileSystem
     * @throws AccessDeniedException
     * @throws Exceptions\ConstraintsException
     * @throws Exceptions\RuntimeException
     * @throws FileNotFoundException
     * @throws UnexpectedValueException
     */
    public function remove(): FileSystem
    {
        if (!$this->storage->doesSatisfyConstraints()) {
            throw $this->storage->getConstraintViolations();
        }

        $this->storage->removeDir();
        return $this;
    }

    /**
     * @inheritDoc
     * @return bool
     * @throws Exceptions\RuntimeException
     * @throws UnexpectedValueException
     */
    public function isDir(): bool
    {
        return $this->storage->isDir();
    }

    /**
     * @param bool $recursive
     * @param int|null $constraints
     * @return DirectoryIterator
     * @throws Exceptions\ConstraintsException
     * @throws Exceptions\RuntimeException
     * @throws UnexpectedValueException
     */
    public function list(bool $recursive = false, ?int $constraints = null): DirectoryIterator
    {
        if (!$this->storage->doesSatisfyConstraints()) {
            throw $this->storage->getConstraintViolations();
        }

        return new DirectoryIterator($this->storage, $recursive, $constraints);
    }

    /**
     * @inheritDoc
     * @param int $mode
     * @param string $algo
     * @param bool $recursive
     * @return string
     * @throws AccessDeniedException
     * @throws Exceptions\ConstraintsException
     * @throws Exceptions\Exception
     * @throws Exceptions\FileNotFoundException
     * @throws Exceptions\RuntimeException
     * @throws Exceptions\UnsupportedException
     * @throws UnexpectedValueException
     */
    public function getHash(int $mode = Hash::CONTENT, string $algo = 'sha256', bool $raw = false, bool $recursive = true): string
    {
        $fileHashes = [];

        /** @var File $entry */
        foreach ($this->list($recursive)->files($this->storage->getConstraints()) as $entry) {
            $fileHashes[] = $entry->getHash($mode, $algo);
        }

        return hash($algo, implode(':', $fileHashes), $raw);
    }

    /**
     * calculate size
     * @param bool $recursive
     * @return int
     * @throws AccessDeniedException
     * @throws Exceptions\Exception
     * @throws Exceptions\UnsupportedException
     * @throws UnexpectedValueException
     */
    public function getSize(bool $recursive = true): int
    {
        $size = 0;

        /** @var File $entry */
        foreach ($this->list($recursive)->files($this->storage->getConstraints()) as $file) {
            $size += $file->getSize();
        }
        return $size;
    }

    /**
     * changes current directory
     * @param string[]|FileSystem[]|Helper\Path[]|Storage\Disk[] $path
     * @return self
     * @throws UnexpectedValueException
     */
    public function cd(...$path): self
    {
        $this->storage->cd($path);
        return $this;
    }

    /**
     * move directory upwards (like /../)
     * @param int $move
     * @return self
     * @throws UnexpectedValueException
     */
    public function up(int $move = 1): self
    {
        $this->storage->cd(array_fill(0, $move, '/..'));
        return $this;
    }

    /**
     * @param string $filename
     * @param int|null $constraints
     * @param string $as
     * @param mixed ...$arguments
     * @return File
     * @throws Exceptions\ConstraintsException
     * @throws Exceptions\RuntimeException
     * @throws UnexpectedValueException
     */
    public function file(string $filename, ?int $constraints = null, string $as = File::class, ...$arguments): File
    {
        if (!$this->storage->doesSatisfyConstraints()) {
            throw $this->storage->getConstraintViolations();
        }

        $dirpath = $this->path()->raw;
        if (is_dir($dirpath)) {
            $dirpath = realpath($dirpath);
        }

        $safepath = $this->path()->safepath;
        if (is_dir($safepath)) {
            $safepath = realpath($safepath);
        }

        /** @var Storage $storage */
        if (is_dir($safepath) && strpos($dirpath, $safepath) === 0) {
            $storage = new Storage\Disk($safepath, str_replace($safepath, '', $dirpath), $filename);
        } else {
            $storage = new Storage\Disk($dirpath, $filename);
        }

        return new $as(
            $storage,
            $constraints ?? $this->storage->getConstraints(),
            ...$arguments
        );
    }

    /**
     * @param string $dirname
     * @param int|null $constraints
     * @param string $as
     * @param mixed ...$arguments
     * @return self
     * @throws Exceptions\ConstraintsException
     * @throws Exceptions\RuntimeException
     * @throws UnexpectedValueException
     */
    public function dir(string $dirname, ?int $constraints = null, string $as = self::class, ...$arguments): Directory
    {
        if (!$this->storage->doesSatisfyConstraints()) {
            throw $this->storage->getConstraintViolations();
        }

        $directory = new $as(
            clone $this->storage(),
            $constraints ?? $this->storage->getConstraints(),
            ...$arguments
        );
        return $directory->cd($dirname);
    }

    /**
     * @param Storage $destination
     * @param int|null $constraints
     * @return static
     * @throws AccessDeniedException
     * @throws Exceptions\ConstraintsException
     * @throws Exceptions\RuntimeException
     * @throws FileNotFoundException
     * @throws UnexpectedValueException
     * @throws UnsupportedException
     */
    public function copyTo(Storage $destination, ?int $constraints = null): static
    {
        if (!$destination instanceof Storage\Disk) {
            throw new UnsupportedException(sprintf('Copying a directory requires the destination storage to be of type Storage\Disk, but got %s instead.', get_debug_type($destination)), 500);
        }

        if (!$this->copyDirectoryTo($destination, $constraints)) {
            throw new AccessDeniedException('unable to copy file', 403);
        }

        return new static($destination);
    }

    /**
     * @param Storage\Disk $destination
     * @param int|null $constraints
     * @return bool
     * @throws AccessDeniedException
     * @throws Exceptions\ConstraintsException
     * @throws Exceptions\RuntimeException
     * @throws FileNotFoundException
     * @throws UnexpectedValueException
     */
    protected function copyDirectoryTo(Storage\Disk $destination, ?int $constraints = null): bool
    {
        $destination->setConstraints($constraints ?? $this->storage->getConstraints());

        $this->checkFileReadPermissions();

        if (!$destination->doesSatisfyConstraints()) {
            throw new AccessDeniedException('Unable to open destination directory.', 403, $destination->getConstraintViolations());
        }

        if ($destination->isDir() && !$destination->isWriteable()) {
            throw new AccessDeniedException('Unable to write to destination file.', 403);
        }

        // actual copy directory to destination: use native functions if possible
        return $this->storage->copyDirectoryTo($destination);
    }
}
